apiVersion: v1
kind: Service
metadata:
  name: hello-app-demo
  namespace: flux-demo
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: hello-app-demo
  type: LoadBalancer
